# Site settings
title: "Hi. Im John Cordero."
description: Software Engineer @<u><a href="https://infowerks.com/">Infowerks</a></u>.
author: John Cordero
email: johncorderox@gmail.com
linkedin: 
github_username: 

baseurl: "/"
 # the subpath of your site, e.g. /blog
url: "https://johncorderox.com" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

