name: John Cordero
description: Hi. I'm John - A Software Engineer based in Los Angeles, CA. I'm currently building at <a href="http://www.myevolutiontravel.com/">Evolution</a>, a travel service company focusing on Ruby on Rails and AWS.
meta_description: "John Cordero | Software Engineer at Archer and Evolution. Ruby on Rails"
blog_written: John
blog_description: Software Developer


aboutPage: true

carousel-evo:
  - image: /assets/images/evo-hdeaer.png
  - image: /assets/images/evo-hdeaer.png


markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate, jemoji]
paginate: 5
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-79158260-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'John Cordero'
authorTwitter:  'johncorderox'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
